spring:
  application:
    name: PaymentManager

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Exchange API
currency:
  api:
    url: "https://api.exchangerate-api.com/v4/latest/"
    delay: 60

  # H2 Database config
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
